In [ ]:
#mount drive
from google.colab import drive
drive.mount('/content/drive')

%cd drive/MyDrive/'BA 2'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[Errno 2] No such file or directory: 'drive/MyDrive/BA 2'
/content/drive/MyDrive/BA 2

In [ ]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import plot_tree, export_text
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [ ]:
#read file and get basic info

myIncome = pd.read_csv('Income2.csv')
myIncome.info()
myIncome

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Experience      210 non-null    int64
 1   GPA             210 non-null    int64
 2   Age             210 non-null    int64
 3   Income          210 non-null    int64
 4   CreditScore     210 non-null    int64
 5   NoCars          210 non-null    int64
 6   ParkingTickets  210 non-null    int64
 7   NewestCarYear   210 non-null    int64
 8   NumberKids      210 non-null    int64
 9   Education       210 non-null    object
dtypes: int64(9), object(1)
memory usage: 16.5+ KB

,Experience,GPA,Age,Income,CreditScore,NoCars,ParkingTickets,NewestCarYear,NumberKids,Education
0,11,242,24,51126,359,2,1,2016,6,HS
1,10,248,25,52306,361,2,2,2018,5,HS
2,11,242,25,51103,361,2,1,2015,6,HS
3,10,248,26,52283,363,2,2,2017,5,HS
4,10,236,24,51444,384,1,2,2019,5,HS
...,...,...,...,...,...,...,...,...,...,...
205,5,389,45,81912,835,2,0,2024,1,PHD
206,6,378,42,81302,839,0,1,2017,0,PHD
207,10,395,46,92559,839,1,1,2021,1,PHD
208,6,378,43,81279,841,0,1,2016,0,PHD
209,10,395,47,92536,841,1,1,2020,1,PHD

In [ ]:
#RESAMPLING - creating more samples

newSamples = myIncome.sample(n=10000, replace=True)
newSamples

,Experience,GPA,Age,Income,CreditScore,NoCars,ParkingTickets,NewestCarYear,NumberKids,Education
97,13,313,32,67905,634,3,1,2015,0,MBA
53,15,323,37,68514,574,3,0,2021,0,MBA
15,10,249,27,51786,476,2,5,2003,3,HS
158,8,391,45,92207,731,1,0,2023,0,PHD
131,7,387,49,84494,678,1,1,2016,0,PHD
...,...,...,...,...,...,...,...,...,...,...
200,9,393,45,92108,823,0,0,2024,1,PHD
115,15,335,33,70990,663,2,2,2013,0,MBA
63,14,319,32,67587,583,1,0,2024,1,MBA
155,15,331,34,71186,730,1,2,2013,0,MBA
150,5,376,42,81401,724,1,1,2018,1,PHD

DATA EXPLORATION

In [ ]:
# Question 5a and 5b
myIncome.info()

# Quesiton 5c
uniqueCreditScores = myIncome['CreditScore'].nunique()
print(uniqueCreditScores)

# Quesiton 5d - number of people with an MBA
mba = (myIncome['Education'] == 'MBA').sum()
print("There are ", mba, " people with an MBA")

# Question 5e - how many features have missing values
missingValues = myIncome.isnull().sum()
print("There are ",missingValues, " features with missing values")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Experience      210 non-null    int64
 1   GPA             210 non-null    int64
 2   Age             210 non-null    int64
 3   Income          210 non-null    int64
 4   CreditScore     210 non-null    int64
 5   NoCars          210 non-null    int64
 6   ParkingTickets  210 non-null    int64
 7   NewestCarYear   210 non-null    int64
 8   NumberKids      210 non-null    int64
 9   Education       210 non-null    object
dtypes: int64(9), object(1)
memory usage: 16.5+ KB
166
There are  91  people with an MBA
There are  Experience        0
GPA               0
Age               0
Income            0
CreditScore       0
NoCars            0
ParkingTickets    0
NewestCarYear     0
NumberKids        0
Education         0
dtype: int64  features with missing values

In [ ]:
#creating dependent and independent variables

y = np.array(newSamples['Education'])
x = newSamples[['Experience','GPA','Age','Income','CreditScore','NoCars','ParkingTickets','NewestCarYear','NumberKids']]

#split data into testing and training data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [ ]:
#Building forest

bagging_MyTree = BaggingClassifier(DecisionTreeClassifier(criterion= 'gini'), n_estimators = 100, max_samples = 1.0, max_features= 3, random_state=42)
bagging_MyTree.fit(x_train, y_train)

#Train the model
bagging_MyTree.fit(x_train, y_train)

#Model predictions
y_pred_bag = bagging_MyTree.predict(x_test)

In [ ]:
# Evaluating the first forest
accuracy_bag = metrics.accuracy_score(y_test, y_pred_bag)
print("Accuracy:", accuracy_bag)

conf_matrix = metrics.confusion_matrix(y_test, y_pred_bag)
print("\nConfusion Matrix:\n", conf_matrix)

Accuracy: 1.0

Confusion Matrix:
 [[ 403    0    0    0]
 [   0  743    0    0]
 [   0    0 1316    0]
 [   0    0    0  538]]

In [ ]:
#all five measures except accuracy as already calculated
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

precision_bag = precision_score(y_test, y_pred_bag, average='weighted')
recall_bag = recall_score(y_test, y_pred_bag, average='weighted')
f1_bag = f1_score(y_test, y_pred_bag, average='weighted')

print("Precision:", precision_bag)
print("Recall:", recall_bag)
print("F1 Score:", f1_bag)

Precision: 1.0
Recall: 1.0
F1 Score: 1.0

In [ ]:
# second random forest

myRF = RandomForestClassifier(n_estimators=500, random_state=42)
myRF.fit(x_train, y_train)

#Model predictions
y_pred_rf = myRF.predict(x_test)

#accuracy of random forest
accuracy_rf = metrics.accuracy_score(y_test, y_pred_rf)
print("Accuracy:", accuracy_rf)

conf_matrix = metrics.confusion_matrix(y_test, y_pred_rf)
print("\nConfusion Matrix:\n", conf_matrix)

Accuracy: 1.0

Confusion Matrix:
 [[ 403    0    0    0]
 [   0  743    0    0]
 [   0    0 1316    0]
 [   0    0    0  538]]

In [ ]:
#all five measures

precision_rf = precision_score(y_test, y_pred_rf, average='weighted')
recall_rf = recall_score(y_test, y_pred_rf, average='weighted')
f1_rf = f1_score(y_test, y_pred_rf, average='weighted')

print("Precision:", precision_rf)
print("Recall:", recall_rf)
print("F1 Score:", f1_rf)